---
- hosts: localhost
  user: root
  become: yes
  connection: ssh

  tasks:

    - name: delete existing repo
      file:
        path: /root/myweb/
        state: absent
      ignore_errors: yes

    - name: getting git repo
      git:
        repo: https://github.com/mithinkumarreddy/myweb-01.git
        dest: /root/myweb
