---
- hosts: dev-2
  user: root
  become: yes
  connection: ssh

  tasks:

    - name: getting link from dlcdn.apache.org
      get_url:
        url: "https://dlcdn.apache.org/tomcat/tomcat-9/v9.0.71/bin/apache-tomcat-9.0.71.tar.gz"
        dest: "/root/"

    - name: untar the apache-tomcat-9.0.71.tar.gz
      command: tar -zxvf apache-tomcat-9.0.71.tar.gz

    - name: rename apache-tomcat-9.0.71.tar.gz to tomcat
      command: mv apache-tomcat-9.0.71 tomcat

    - name: install java11
      command: amazon-linux-extras install java-openjdk11 -y 

    - name: modify context.xml file
      template:
        src: context.xml
        dest: /root/tomcat/webapps/manager/META-INF/context.xml

    - name: modify tomcat-users.xml file 
      template:
        src: tomcat-users.xml
        dest: /root/tomcat/conf/tomcat-users.xml

    - name: start tomcat
      shell: nohup /root/tomcat/bin/startup.sh
