---
- hosts: dev-2
  user: root
  become: yes
  connection: ssh

  tasks:

    - name: to check tomcat present or not
      file:
        path: /root/tomcat
        state: directory
      register: directory_check

    - block:
      - name: Task 1
        debug:
          msg: "Task 1"

      - name: Task 2
        debug:
          msg: "Task 2"

      when: not directory_check.stat.exists is defined
